### ISSUE TITLE
Certificates file is several years old

### ISSUE THREAD

**Issue by soatok** [omise/omise-php#112]
https://github.com/omise/omise-php/blob/master/data/ca_certificates.pem

Might be worth checking into https://github.com/paragonie/certainty in the future to keep them up-to-date?

**Comment by guzzilar** [comment]
@soatok thanks for reporting. 👍 
However, as the CA Certificate file is authorized by our API server and still valid, we wouldn't need to replace it at the moment.

**Comment by soatok** [comment]
Does your old CA Certificates file work with the new Lets Encrypt CA?
