### ISSUE TITLE
[Question] How to pass custom CURLOPT option

### ISSUE THREAD

**Issue by dev-hyperweb** [omise/omise-php#136]
I need to pass some option to use for make it more secure and fastest.
Example: CURLOPT_INTERFACE

How to pass something like this into curl object ?

**Comment by aashishgurung** [comment]
Thank you for reaching out. Is this still relevant? Can you please provide more details on what you are trying to achieve?

**Comment by dev-hyperweb** [comment]
I'm not using omise anymore, but I will explain what I want to do.

example: I want to add some curl option like this

curl_setopt($ch, CURLOPT_INTERFACE, "XXX.XXX.XXX.XXX"); 
to use my second IPs.
