### ISSUE TITLE
Live server issue 

### ISSUE THREAD

**Issue by maheshki4consulting** [omise/omise-php#137]
Payment method working properly on the local server. But it's showing an error on the live server.

Error: OmiseApiResource.php: count(): Parameter must be an array or an object that implements Countable

Please help

**Comment by maheshki4consulting** [comment]
> Payment method working properly on the local server. But it's showing an error on the live server.
> 
> Error: OmiseApiResource.php: count(): Parameter must be an array or an object that implements Countable
> 
> Please help

**Comment by maheshki4consulting** [comment]
PLease update

**Comment by bigomise** [comment]
Please could you provide more information here?
1. Which version of Omise-PHP are you using?
2. Which version of PHP are you using on your server and your local?

**Comment by bigomise** [comment]
> omise-php-2.11.2
> Php version : 7.4

both local and server are the same?

**Comment by bigomise** [comment]
and how this error happens, please?

It would be grateful if you could provide your code snippet. (Please make sure that there is no any sensitive information in the code snippet)
