### ISSUE TITLE
How i use charge::retrive and sort by created desc ? 

### ISSUE THREAD

**Issue by nutjaa** [omise/omise-php#14]
My code 
```
$page = $requests->input('page' , 0 ); 
$id = '?offset='.($page*15).'&limit=15' ;
$charges = \OmiseCharge::retrieve($id) ;
```
it seem always sort by created asc . 

Thanks

**Comment by robinclart** [comment]
Hi @nutja as for now we don't support a 'sort' option. But you can palliate to this by using the pagination or date scope to only retrieve a specific set of charges given a pair of 'from' and 'to' dates and the 'offset' and 'limit' parameters. You can learn about those in more details in [our pagination docs](https://docs.omise.co/api/pagination/).

Thanks for your feedback. We'll see if we can add this to the next version of our API.

**Comment by guzzilar** [comment]
just note that we already provided `order` parameter that allows people to retrieve a list of an object sorting by `chronological` (or `reverse_chronological`)

from [our pagination and lists docs](https://www.omise.co/api-pagination)
😊
