### ISSUE TITLE
Wrong OMISE_PHP_LIB_VERSION version in release tag v2.12.0

### ISSUE THREAD

**Issue by zdk** [omise/omise-php#165]
### Expected behavior

Expect OMISE_PHP_LIB_VERSION matches with release version https://github.com/omise/omise-php/releases/tag/v2.12.0

### Actual behavior

The OMISE_PHP_LIB_VERSION is still `2.11.2`
as shown in https://github.com/omise/omise-php/blame/v2.12.0/lib/omise/res/OmiseApiResource.php#L3

### Steps to reproduce the issue

Install omise-php v2.12.0

### Screenshots

<img width="1680" alt="301034160-e10d166a-8f56-46a0-895d-8e5ac6cc89d3" src="https://github.com/omise/omise-php/assets/5758/f041391b-38c5-4608-994c-4e5e077f7217">

### Name and version information

https://github.com/omise/omise-php/releases/tag/v2.12.0

**Comment by aashishgurung** [comment]
@zdk Thank you for bringing this issue to our attention. We have updated to the right version to resolve it.
