### ISSUE TITLE
A PHPDoc return value declaration for the \OmiseApiResource::isDestroyed() method is wrong

### ISSUE THREAD

**Issue by dmitry-fedyuk** [omise/omise-php#43]
https://github.com/omise/omise-php/blob/v2.5.0/lib/omise/res/OmiseApiResource.php#L258

Should be:
```
@return bool|null
```

**Comment by guzzilar** [comment]
@dmitry-fedyuk Thanks 👍 !

Do you wanna submit a PR for that one?
I'm ready to merge that PR 😁 

Nam.

**Comment by guzzilar** [comment]
Note, this ticket was solved at PR #57. 

Im going to close it now.
Thanks for submitted the ticket!
