### ISSUE TITLE
Add a programmatic way to check whether the 3D Secure validation is enabled for a given Omise account

### ISSUE THREAD

**Issue by dmitrii-fediuk** [omise/omise-php#52]

**Comment by fred** [comment]
Hi Dmitry,
Currently it's not possible to fetch if 3DSecure is enabled or not via API. If that is what you wanted to know. Neither in the charges object there is a way to know programmatically.
If have to implement a solution that would work for both type of accounts, our recommendation for now is to always pass `return_uri` and always redirect. If the account is non-3ds, then the redirect will still work but skip the bank authentication. 
We are aware of this limitation and have plans to improve it.
Cheers.

**Comment by pkollitsch** [comment]
Is it right to think, that if the status of a charge is "success" then it is not 3D Secure? I am handling this issue it that way at the moment. 

- omise.js to retrieve a token
- form processing charges the token
- if status = success then it's paid and not 3d secure
- if status = pending then it's 3d secure and the payment is not yet received
- any other status is failed. 

after a while then I check for the charge and see if it's still pending or changed to success or failure.

The main issue here is, that if 3d secure is enabled we don't have a sale yet when the customer arrives at the return_uri.

**Comment by guzzilar** [comment]
@pkollitsch yes, it can be assumed that if the charge status is `pending` means the charge process (might) requires a 3-D Secure validation.

More accurately can be: if 
```php
$charge['status']     = pending
$charge['authorized'] = false
$charge['paid']       = false
```
then we can redirect user out to `charge.authorize_uri`.
