### ISSUE TITLE
OmiseCardList::Count() works incorrect 

### ISSUE THREAD

**Issue by 1dnmr** [omise/omise-php#66]
Hello,

count from OmiseObject work incorrect.

Please add to OmiseCardList.php this function:
    /**
     *
     * @return integer
     */
    public function count()
    {
        if (array_key_exists('data', $this->_values) === true) {
            return count($this->_values['data']);
        } else {
            return 0;
        }
    }

Also please add following function:
    /**
     * @param  integer $index
     *
     * @return OmiseCard
     */
    public function getCardByIndex($index)
    {
        if (array_key_exists('data', $this->_values) === true && $index >= 0 && $index < $this->count()) {
            return $this->_values['data'][$index];
        } else {
            return null;
        }
    }

**Comment by guzzilar** [comment]
Hi @1dnmr 

Thanks for report and submit your code here.
I see for your point on `count()` method. By the way, to retrieve a 'data total', I suggest you to implement with the following approach instead.

```php
$charges = OmiseCharge::retrieve();

echo $charges['total'];
```

It's because `count($this->_values['data'])` will just only give you a total of an array that you specify in `limit` parameter (default: 20) but not exactly total items that you have in your account.

For example , if you have 150 charge transactions.
```php
$charges = OmiseCharge::retrieve();

echo $charges->count(); // would return just 20, not 150.
```

Anyway, I'll consider more on above use case and interface. Thanks again :)

**Comment by 1dnmr** [comment]
But this is not about Charge, as I mention its about  OmiseCardList object. This object does not have 'total'.

**Comment by 1dnmr** [comment]
@guzzilar But this is not about Charge, as I mention its about OmiseCardList object. This object does not have 'total'.

**Comment by guzzilar** [comment]
@1dnmr Sorry I may not fully understand your problem. Can you explain me more on your use case or any example code that you've implemented with and found the issue?

If you want to get a total of cards that belong to a customer, you can go with
```php
$customers = OmiseCustomer::retrieve('cust_test_xxx');
$cards     = $customers->cards();

echo $cards['total'];
```

**Comment by 1dnmr** [comment]
Yes, it works, sorry.
I tried before use this code. And count() not work as expected.
```
$customers = OmiseCustomer::retrieve('cust_test_xxx');
$cards     = $customers->cards();

echo $cards->count();
```
Also how to retrieve card by Index with existing code?
I added new method  getCardByIndex to do this.

**Comment by guzzilar** [comment]
@1dnmr  Haha no worry.

For retrieve card by index, looking at your code I think this is what you are looking for?
```php
$customers = OmiseCustomer::retrieve('cust_test_53q3u1qxziva8mhw9ld');
$cards     = $customers->cards();

$card_at_index_2 = $cards['data'][2];
// Or 

echo $cards['data'][2]['id']; // card_test_xxx
```

**Comment by 1dnmr** [comment]
@guzzilar Right, thank you! :)

**Comment by guzzilar** [comment]
Welcome :D 👍
