### ISSUE TITLE
Proposal: implement extension for Omnipay

### ISSUE THREAD

**Issue by 1dnmr** [omise/omise-php#78]
Implement extension for [Omnipay](https://github.com/thephpleague/omnipay)

Omnipay is a collection of packages which all depend on the [omnipay/common](https://github.com/thephpleague/omnipay-common) package to provide a consistent interface. There are no dependencies on official payment gateway PHP packages - we prefer to work with the HTTP API directly. Under the hood, we use the popular and [powerful PHP-HTTP](http://docs.php-http.org/en/latest/index.html) library to make HTTP requests. A [Guzzle](http://guzzlephp.org/) adapter is required by default, when using league/omnipay.

New gateways can be created by cloning the layout of an existing package. When choosing a name for your package, please don’t use the omnipay vendor prefix, as this implies that it is officially supported. You should use your own username as the vendor prefix, and prepend omnipay- to the package name to make it clear that your package works with Omnipay. For example, if your GitHub username was santa, and you were implementing the giftpay payment library, a good name for your composer package would be santa/omnipay-giftpay.

[Build your own driver]( https://omnipay.thephpleague.com/gateways/build-your-own/)

**Comment by dilab** [comment]
https://github.com/Spacebib/omnipay-omise/tree/master

**Comment by 1dnmr** [comment]
@dilab cool! thanks

**Comment by aashishgurung** [comment]
Thanks @dilab for creating the extension. Please free to contact us if you need any help.
